package com.example.f_chat.entity;

import java.util.List;

public class Conversation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.id
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.first_id
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    private Integer firstId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.second_id
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    private Integer secondId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.first_view
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    private Integer firstView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation.second_view
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    private Integer secondView;

    private Message lastMsg;

    private List<Message> messageList;

    private Integer orderId;

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Conversation(Integer id, Integer firstId, Integer secondId, Integer firstView, Integer secondView, Message lastMsg, List<Message> messageList, Integer orderId) {
        this.id = id;
        this.firstId = firstId;
        this.secondId = secondId;
        this.firstView = firstView;
        this.secondView = secondView;
        this.lastMsg = lastMsg;
        this.messageList = messageList;
        this.orderId = orderId;
    }

    public List<Message> getMessageList() {
        return messageList;
    }

    public void setMessageList(List<Message> messageList) {
        this.messageList = messageList;
    }

    public Message getLastMsg() {
        return lastMsg;
    }

    public void setLastMsg(Message lastMsg) {
        this.lastMsg = lastMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.id
     *
     * @return the value of conversation.id
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.id
     *
     * @param id the value for conversation.id
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.first_id
     *
     * @return the value of conversation.first_id
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    public Integer getFirstId() {
        return firstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.first_id
     *
     * @param firstId the value for conversation.first_id
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    public void setFirstId(Integer firstId) {
        this.firstId = firstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.second_id
     *
     * @return the value of conversation.second_id
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    public Integer getSecondId() {
        return secondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.second_id
     *
     * @param secondId the value for conversation.second_id
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    public void setSecondId(Integer secondId) {
        this.secondId = secondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.first_view
     *
     * @return the value of conversation.first_view
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    public Integer getFirstView() {
        return firstView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.first_view
     *
     * @param firstView the value for conversation.first_view
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    public void setFirstView(Integer firstView) {
        this.firstView = firstView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation.second_view
     *
     * @return the value of conversation.second_view
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    public Integer getSecondView() {
        return secondView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation.second_view
     *
     * @param secondView the value for conversation.second_view
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    public void setSecondView(Integer secondView) {
        this.secondView = secondView;
    }

    public Conversation(Integer id, Integer firstId, Integer secondId, Integer firstView, Integer secondView) {
        this.id = id;
        this.firstId = firstId;
        this.secondId = secondId;
        this.firstView = firstView;
        this.secondView = secondView;
    }

    public Conversation() {
    }

    public Conversation(Integer id, Integer firstId, Integer secondId, Integer firstView, Integer secondView, Message lastMsg) {
        this.id = id;
        this.firstId = firstId;
        this.secondId = secondId;
        this.firstView = firstView;
        this.secondView = secondView;
        this.lastMsg = lastMsg;
    }

    public Conversation(Integer id, Integer firstId, Integer secondId, Integer firstView, Integer secondView, Message lastMsg, List<Message> messageList) {
        this.id = id;
        this.firstId = firstId;
        this.secondId = secondId;
        this.firstView = firstView;
        this.secondView = secondView;
        this.lastMsg = lastMsg;
        this.messageList = messageList;
    }
}