package com.example.f_chat.entity;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.conversation_id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    private Integer conversationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.from_id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    private Integer fromId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.to_id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    private Integer toId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.type
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.status
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_push
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    private Integer isPush;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.other_msg
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    private String otherMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.time
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.conversation_id
     *
     * @return the value of message.conversation_id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public Integer getConversationId() {
        return conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.conversation_id
     *
     * @param conversationId the value for message.conversation_id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public void setConversationId(Integer conversationId) {
        this.conversationId = conversationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.from_id
     *
     * @return the value of message.from_id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public Integer getFromId() {
        return fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.from_id
     *
     * @param fromId the value for message.from_id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.to_id
     *
     * @return the value of message.to_id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public Integer getToId() {
        return toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.to_id
     *
     * @param toId the value for message.to_id
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public void setToId(Integer toId) {
        this.toId = toId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_push
     *
     * @return the value of message.is_push
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public Integer getIsPush() {
        return isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_push
     *
     * @param isPush the value for message.is_push
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public void setIsPush(Integer isPush) {
        this.isPush = isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.other_msg
     *
     * @return the value of message.other_msg
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public String getOtherMsg() {
        return otherMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.other_msg
     *
     * @param otherMsg the value for message.other_msg
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public void setOtherMsg(String otherMsg) {
        this.otherMsg = otherMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.time
     *
     * @return the value of message.time
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.time
     *
     * @param time the value for message.time
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Sat Jul 30 21:19:55 CST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }
}