package com.example.f_chat.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.realname
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phone
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.status
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.sex
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.city
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.describex
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    private String describex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.img
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.realname
     *
     * @return the value of userinfo.realname
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.realname
     *
     * @param realname the value for userinfo.realname
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phone
     *
     * @return the value of userinfo.phone
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phone
     *
     * @param phone the value for userinfo.phone
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.status
     *
     * @return the value of userinfo.status
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.status
     *
     * @param status the value for userinfo.status
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.sex
     *
     * @return the value of userinfo.sex
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.sex
     *
     * @param sex the value for userinfo.sex
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.city
     *
     * @return the value of userinfo.city
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.city
     *
     * @param city the value for userinfo.city
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.describex
     *
     * @return the value of userinfo.describex
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public String getDescribex() {
        return describex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.describex
     *
     * @param describex the value for userinfo.describex
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public void setDescribex(String describex) {
        this.describex = describex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.img
     *
     * @return the value of userinfo.img
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.img
     *
     * @param img the value for userinfo.img
     *
     * @mbg.generated Wed Jul 06 20:59:31 CST 2022
     */
    public void setImg(String img) {
        this.img = img;
    }

    public User() {
    }

    public User(Integer id, String username, String realname, String phone, Integer status, Integer sex, String city, String describex, String img) {
        this.id = id;
        this.username = username;
        this.realname = realname;
        this.phone = phone;
        this.status = status;
        this.sex = sex;
        this.city = city;
        this.describex = describex;
        this.img = img;
    }

    public User(String phone) {
        this.phone = phone;
        this.status=0;
    }
}

