package com.example.f_chat.dao;

import com.example.f_chat.entity.Conversation;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConversationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    int insert(Conversation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    Conversation selectByPrimaryKey(Integer id);
    Conversation selectByPrimaryKeyPlus(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    List<Conversation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table conversation
     *
     * @mbg.generated Tue Jul 26 10:09:57 CST 2022
     */
    int updateByPrimaryKey(Conversation record);

    List<Conversation> selectConversations(Integer id);
    Conversation selectConversationByUserIds(@Param("id1") Integer  id1,@Param("id2") Integer id2);
}