package com.example.f_chat.dao;

import com.example.f_chat.entity.Relation;
import com.example.f_chat.entity.User;

import java.util.List;

public interface RelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Fri Jul 29 22:14:55 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Fri Jul 29 22:14:55 CST 2022
     */
    int insert(Relation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Fri Jul 29 22:14:55 CST 2022
     */
    Relation selectByPrimaryKey(Integer id);
    List<Relation> selectByHost(Integer u_host);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Fri Jul 29 22:14:55 CST 2022
     */
    List<Relation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relation
     *
     * @mbg.generated Fri Jul 29 22:14:55 CST 2022
     */
    int updateByPrimaryKey(Relation record);

    Relation selectByIds(Integer id1,Integer id2);

}